name: Bicep CI

on:
  push:
    paths:
      - 'infrastructure/**/*.bicep'
  pull_request:
    paths:
      - 'infrastructure/**/*.bicep'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Azure CLI and Bicep
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az bicep install

      - name: Validate Bicep files
        run: |
          find infrastructure -name '*.bicep' -print0 | xargs -0 -n1 az bicep build --stdout
